<a href="https://colab.research.google.com/github/disha526/Titanic-Survival-Prediction-Using-Machine-Learning/blob/main/Pandas_Data_Analysis_MS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Load the CSV file into pandas DataFrame
#Display first 5 rows
# Display last 10 rows
# Get column names
# Select only Name and Marks columns
# Find total number of students
# Get data type of each column
# Show details using .info()

In [ ]:
import pandas as pd
df = pd.read_csv("student_data.csv")
df

    StudentID      Name  Age  Gender Course  Marks    City  Attendance
0           1      Amit   20    Male    BCA     78  Mumbai          85
1           2      Neha   21  Female    BCA     82    Pune          90
2           3     Rahul   19    Male    BSc     65  Nagpur          75
3           4     Pooja   22  Female   BCom     88  Mumbai          92
4           5     Arjun   20    Male    BCA     55    Pune          60
5           6     Sneha   23  Female    BSc     91  Nashik          95
6           7      Ravi   21    Male   BCom     72  Nagpur          80
7           8     Kajal   20  Female    BCA     67  Mumbai          70
8           9     Ankit   22    Male    BSc     49    Pune          65
9          10     Meena   19  Female   BCom     77  Nashik          85
10         11     Vikas   21    Male    BCA     83  Mumbai          88
11         12      Ritu   20  Female    BSc     69    Pune          78
12         13     Sahil   23    Male   BCom     90  Nagpur          92
13         14     Divya   22  Female    BCA     74  Mumbai          80
14         15     Karan   19    Male    BSc     58  Nashik          72
15         16    Simran   21  Female   BCom     81    Pune          87
16         17    Deepak   20    Male    BCA     66  Mumbai          75
17         18     Nisha   22  Female    BSc     92  Nagpur          96
18         19     Rohit   23    Male   BCom     70    Pune          78
19         20     Payal   21  Female    BCA     85  Nashik          89
20         21    Manish   20    Male    BSc     60  Mumbai          70
21         22    Anjali   19  Female   BCom     76    Pune          82
22         23     Varun   22    Male    BCA     88  Nagpur          91
23         24    Shreya   23  Female    BSc     93  Mumbai          97
24         25     Akash   21    Male   BCom     54  Nashik          60
25         26      Tina   20  Female    BCA     79    Pune          85
26         27     Harsh   22    Male    BSc     68  Mumbai          74
27         28     Komal   21  Female   BCom     82  Nagpur          88
28         29     Nitin   23    Male    BCA     47    Pune          55
29         30     Priya   20  Female    BSc     86  Nashik          90
30         31      Ajay   19    Male   BCom     73  Mumbai          80
31         32    Rashmi   21  Female    BCA     84    Pune          89
32         33     Sunil   22    Male    BSc     62  Nagpur          68
33         34     Rekha   23  Female   BCom     91  Mumbai          94
34         35    Sameer   20    Male    BCA     59  Nashik          65
35         36     Aarti   21  Female    BSc     77    Pune          83
36         37     Vinay   22    Male   BCom     85  Mumbai          88
37         38     Swati   23  Female    BCA     92  Nagpur          96
38         39    Gaurav   21    Male    BSc     71    Pune          79
39         40     Seema   20  Female   BCom     64  Nashik          72
40         41  Abhishek   22    Male    BCA     80  Mumbai          85
41         42     Kriti   23  Female    BSc     89    Pune          92
42         43     Mohit   20    Male   BCom     56  Nagpur          65
43         44    Sonali   21  Female    BCA     87  Mumbai          90
44         45     Imran   22    Male    BSc     74    Pune          80
45         46     Farah   23  Female   BCom     83  Nashik          88
46         47    Sachin   20    Male    BCA     69  Mumbai          75
47         48   Pallavi   21  Female    BSc     95  Nagpur          98
48         49    Naresh   22    Male   BCom     61    Pune          70
49         50      Riya   23  Female    BCA     90  Mumbai          93

In [ ]:
df.head(5)

   StudentID   Name  Age  Gender Course  Marks    City  Attendance
0          1   Amit   20    Male    BCA     78  Mumbai          85
1          2   Neha   21  Female    BCA     82    Pune          90
2          3  Rahul   19    Male    BSc     65  Nagpur          75
3          4  Pooja   22  Female   BCom     88  Mumbai          92
4          5  Arjun   20    Male    BCA     55    Pune          60

In [ ]:
df.columns

Index(['StudentID', 'Name', 'Age', 'Gender', 'Course', 'Marks', 'City',
       'Attendance'],
      dtype='object')

In [ ]:
df.columns

Index(['StudentID', 'Name', 'Age', 'Gender', 'Course', 'Marks', 'City',
       'Attendance'],
      dtype='object')

In [ ]:
df["Name"]

0         Amit
1         Neha
2        Rahul
3        Pooja
4        Arjun
5        Sneha
6         Ravi
7        Kajal
8        Ankit
9        Meena
10       Vikas
11        Ritu
12       Sahil
13       Divya
14       Karan
15      Simran
16      Deepak
17       Nisha
18       Rohit
19       Payal
20      Manish
21      Anjali
22       Varun
23      Shreya
24       Akash
25        Tina
26       Harsh
27       Komal
28       Nitin
29       Priya
30        Ajay
31      Rashmi
32       Sunil
33       Rekha
34      Sameer
35       Aarti
36       Vinay
37       Swati
38      Gaurav
39       Seema
40    Abhishek
41       Kriti
42       Mohit
43      Sonali
44       Imran
45       Farah
46      Sachin
47     Pallavi
48      Naresh
49        Riya
Name: Name, dtype: object

In [ ]:
df[["Name","Marks"]]

        Name  Marks
0       Amit     78
1       Neha     82
2      Rahul     65
3      Pooja     88
4      Arjun     55
5      Sneha     91
6       Ravi     72
7      Kajal     67
8      Ankit     49
9      Meena     77
10     Vikas     83
11      Ritu     69
12     Sahil     90
13     Divya     74
14     Karan     58
15    Simran     81
16    Deepak     66
17     Nisha     92
18     Rohit     70
19     Payal     85
20    Manish     60
21    Anjali     76
22     Varun     88
23    Shreya     93
24     Akash     54
25      Tina     79
26     Harsh     68
27     Komal     82
28     Nitin     47
29     Priya     86
30      Ajay     73
31    Rashmi     84
32     Sunil     62
33     Rekha     91
34    Sameer     59
35     Aarti     77
36     Vinay     85
37     Swati     92
38    Gaurav     71
39     Seema     64
40  Abhishek     80
41     Kriti     89
42     Mohit     56
43    Sonali     87
44     Imran     74
45     Farah     83
46    Sachin     69
47   Pallavi     95
48    Naresh     61
49      Riya     90

In [ ]:
len(df)

50

In [ ]:
df.dtypes

StudentID      int64
Name          object
Age            int64
Gender        object
Course        object
Marks          int64
City          object
Attendance     int64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   50 non-null     int64
 1   Name        50 non-null     object
 2   Age         50 non-null     int64
 3   Gender      50 non-null     object
 4   Course      50 non-null     object
 5   Marks       50 non-null     int64
 6   City        50 non-null     object
 7   Attendance  50 non-null     int64
dtypes: int64(4), object(4)
memory usage: 3.3+ KB

In [ ]:
df.sort_values(by="Marks")

    StudentID      Name  Age  Gender Course  Marks    City  Attendance
28         29     Nitin   23    Male    BCA     47    Pune          55
8           9     Ankit   22    Male    BSc     49    Pune          65
24         25     Akash   21    Male   BCom     54  Nashik          60
4           5     Arjun   20    Male    BCA     55    Pune          60
42         43     Mohit   20    Male   BCom     56  Nagpur          65
14         15     Karan   19    Male    BSc     58  Nashik          72
34         35    Sameer   20    Male    BCA     59  Nashik          65
20         21    Manish   20    Male    BSc     60  Mumbai          70
48         49    Naresh   22    Male   BCom     61    Pune          70
32         33     Sunil   22    Male    BSc     62  Nagpur          68
39         40     Seema   20  Female   BCom     64  Nashik          72
2           3     Rahul   19    Male    BSc     65  Nagpur          75
16         17    Deepak   20    Male    BCA     66  Mumbai          75
7           8     Kajal   20  Female    BCA     67  Mumbai          70
26         27     Harsh   22    Male    BSc     68  Mumbai          74
11         12      Ritu   20  Female    BSc     69    Pune          78
46         47    Sachin   20    Male    BCA     69  Mumbai          75
18         19     Rohit   23    Male   BCom     70    Pune          78
38         39    Gaurav   21    Male    BSc     71    Pune          79
6           7      Ravi   21    Male   BCom     72  Nagpur          80
30         31      Ajay   19    Male   BCom     73  Mumbai          80
44         45     Imran   22    Male    BSc     74    Pune          80
13         14     Divya   22  Female    BCA     74  Mumbai          80
21         22    Anjali   19  Female   BCom     76    Pune          82
9          10     Meena   19  Female   BCom     77  Nashik          85
35         36     Aarti   21  Female    BSc     77    Pune          83
0           1      Amit   20    Male    BCA     78  Mumbai          85
25         26      Tina   20  Female    BCA     79    Pune          85
40         41  Abhishek   22    Male    BCA     80  Mumbai          85
15         16    Simran   21  Female   BCom     81    Pune          87
1           2      Neha   21  Female    BCA     82    Pune          90
27         28     Komal   21  Female   BCom     82  Nagpur          88
45         46     Farah   23  Female   BCom     83  Nashik          88
10         11     Vikas   21    Male    BCA     83  Mumbai          88
31         32    Rashmi   21  Female    BCA     84    Pune          89
36         37     Vinay   22    Male   BCom     85  Mumbai          88
19         20     Payal   21  Female    BCA     85  Nashik          89
29         30     Priya   20  Female    BSc     86  Nashik          90
43         44    Sonali   21  Female    BCA     87  Mumbai          90
3           4     Pooja   22  Female   BCom     88  Mumbai          92
22         23     Varun   22    Male    BCA     88  Nagpur          91
41         42     Kriti   23  Female    BSc     89    Pune          92
49         50      Riya   23  Female    BCA     90  Mumbai          93
12         13     Sahil   23    Male   BCom     90  Nagpur          92
5           6     Sneha   23  Female    BSc     91  Nashik          95
33         34     Rekha   23  Female   BCom     91  Mumbai          94
37         38     Swati   23  Female    BCA     92  Nagpur          96
17         18     Nisha   22  Female    BSc     92  Nagpur          96
23         24    Shreya   23  Female    BSc     93  Mumbai          97
47         48   Pallavi   21  Female    BSc     95  Nagpur          98

#- Filter students with Marks > 80
# Get all students from Mumbai
# Find students with Attendance < 70
# Get average Marks of all students
# Find highest Marks scored
# Count number of male and female students
# Get students enrolled in BCA course
# Sort students by Marks (descending)
# Select first 3 students from Pune

In [ ]:
df_marks_80 = df[df['Marks'] > 80]
print(df_marks_80)

    StudentID     Name  Age  Gender Course  Marks    City  Attendance
1           2     Neha   21  Female    BCA     82    Pune          90
3           4    Pooja   22  Female   BCom     88  Mumbai          92
5           6    Sneha   23  Female    BSc     91  Nashik          95
10         11    Vikas   21    Male    BCA     83  Mumbai          88
12         13    Sahil   23    Male   BCom     90  Nagpur          92
15         16   Simran   21  Female   BCom     81    Pune          87
17         18    Nisha   22  Female    BSc     92  Nagpur          96
19         20    Payal   21  Female    BCA     85  Nashik          89
22         23    Varun   22    Male    BCA     88  Nagpur          91
23         24   Shreya   23  Female    BSc     93  Mumbai          97
27         28    Komal   21  Female   BCom     82  Nagpur          88
29         30    Priya   20  Female    BSc     86  Nashik          90
31         32   Rashmi   21  Female    BCA     84    Pune          89
33         34    Rekha   23  Female   BCom     91  Mumbai          94
36         37    Vinay   22    Male   BCom     85  Mumbai          88
37         38    Swati   23  Female    BCA     92  Nagpur          96
41         42    Kriti   23  Female    BSc     89    Pune          92
43         44   Sonali   21  Female    BCA     87  Mumbai          90
45         46    Farah   23  Female   BCom     83  Nashik          88
47         48  Pallavi   21  Female    BSc     95  Nagpur          98
49         50     Riya   23  Female    BCA     90  Mumbai          93

In [ ]:
df_mumbai = df[df['City'] == "Mumbai"]
print(df_mumbai)

    StudentID      Name  Age  Gender Course  Marks    City  Attendance
0           1      Amit   20    Male    BCA     78  Mumbai          85
3           4     Pooja   22  Female   BCom     88  Mumbai          92
7           8     Kajal   20  Female    BCA     67  Mumbai          70
10         11     Vikas   21    Male    BCA     83  Mumbai          88
13         14     Divya   22  Female    BCA     74  Mumbai          80
16         17    Deepak   20    Male    BCA     66  Mumbai          75
20         21    Manish   20    Male    BSc     60  Mumbai          70
23         24    Shreya   23  Female    BSc     93  Mumbai          97
26         27     Harsh   22    Male    BSc     68  Mumbai          74
30         31      Ajay   19    Male   BCom     73  Mumbai          80
33         34     Rekha   23  Female   BCom     91  Mumbai          94
36         37     Vinay   22    Male   BCom     85  Mumbai          88
40         41  Abhishek   22    Male    BCA     80  Mumbai          85
43         44    Sonali   21  Female    BCA     87  Mumbai          90
46         47    Sachin   20    Male    BCA     69  Mumbai          75
49         50      Riya   23  Female    BCA     90  Mumbai          93

In [ ]:
df_attend_70 = df[df['Attendance']< 70]
display(df_attend_70)

    StudentID    Name  Age Gender Course  Marks    City  Attendance
4           5   Arjun   20   Male    BCA     55    Pune          60
8           9   Ankit   22   Male    BSc     49    Pune          65
24         25   Akash   21   Male   BCom     54  Nashik          60
28         29   Nitin   23   Male    BCA     47    Pune          55
32         33   Sunil   22   Male    BSc     62  Nagpur          68
34         35  Sameer   20   Male    BCA     59  Nashik          65
42         43   Mohit   20   Male   BCom     56  Nagpur          65

In [ ]:
df_avg_marks = df['Marks'].mean()
df_avg_marks

np.float64(75.34)

In [ ]:
df_high_marks = df['Marks'].max()
df_high_marks

95

In [ ]:

gender_count = df['Gender'].value_counts()
display(gender_count)

Gender
Male      25
Female    25
Name: count, dtype: int64

In [ ]:
df_bca = df[df['Course']=='BCA']
display(df_bca)

    StudentID      Name  Age  Gender Course  Marks    City  Attendance
0           1      Amit   20    Male    BCA     78  Mumbai          85
1           2      Neha   21  Female    BCA     82    Pune          90
4           5     Arjun   20    Male    BCA     55    Pune          60
7           8     Kajal   20  Female    BCA     67  Mumbai          70
10         11     Vikas   21    Male    BCA     83  Mumbai          88
13         14     Divya   22  Female    BCA     74  Mumbai          80
16         17    Deepak   20    Male    BCA     66  Mumbai          75
19         20     Payal   21  Female    BCA     85  Nashik          89
22         23     Varun   22    Male    BCA     88  Nagpur          91
25         26      Tina   20  Female    BCA     79    Pune          85
28         29     Nitin   23    Male    BCA     47    Pune          55
31         32    Rashmi   21  Female    BCA     84    Pune          89
34         35    Sameer   20    Male    BCA     59  Nashik          65
37         38     Swati   23  Female    BCA     92  Nagpur          96
40         41  Abhishek   22    Male    BCA     80  Mumbai          85
43         44    Sonali   21  Female    BCA     87  Mumbai          90
46         47    Sachin   20    Male    BCA     69  Mumbai          75
49         50      Riya   23  Female    BCA     90  Mumbai          93

In [ ]:
df_sort_descend = df.sort_values(by='Marks', ascending=False)
display(df_sort_descend)

    StudentID      Name  Age  Gender Course  Marks    City  Attendance
47         48   Pallavi   21  Female    BSc     95  Nagpur          98
23         24    Shreya   23  Female    BSc     93  Mumbai          97
17         18     Nisha   22  Female    BSc     92  Nagpur          96
37         38     Swati   23  Female    BCA     92  Nagpur          96
33         34     Rekha   23  Female   BCom     91  Mumbai          94
5           6     Sneha   23  Female    BSc     91  Nashik          95
12         13     Sahil   23    Male   BCom     90  Nagpur          92
49         50      Riya   23  Female    BCA     90  Mumbai          93
41         42     Kriti   23  Female    BSc     89    Pune          92
3           4     Pooja   22  Female   BCom     88  Mumbai          92
22         23     Varun   22    Male    BCA     88  Nagpur          91
43         44    Sonali   21  Female    BCA     87  Mumbai          90
29         30     Priya   20  Female    BSc     86  Nashik          90
19         20     Payal   21  Female    BCA     85  Nashik          89
36         37     Vinay   22    Male   BCom     85  Mumbai          88
31         32    Rashmi   21  Female    BCA     84    Pune          89
10         11     Vikas   21    Male    BCA     83  Mumbai          88
45         46     Farah   23  Female   BCom     83  Nashik          88
1           2      Neha   21  Female    BCA     82    Pune          90
27         28     Komal   21  Female   BCom     82  Nagpur          88
15         16    Simran   21  Female   BCom     81    Pune          87
40         41  Abhishek   22    Male    BCA     80  Mumbai          85
25         26      Tina   20  Female    BCA     79    Pune          85
0           1      Amit   20    Male    BCA     78  Mumbai          85
35         36     Aarti   21  Female    BSc     77    Pune          83
9          10     Meena   19  Female   BCom     77  Nashik          85
21         22    Anjali   19  Female   BCom     76    Pune          82
13         14     Divya   22  Female    BCA     74  Mumbai          80
44         45     Imran   22    Male    BSc     74    Pune          80
30         31      Ajay   19    Male   BCom     73  Mumbai          80
6           7      Ravi   21    Male   BCom     72  Nagpur          80
38         39    Gaurav   21    Male    BSc     71    Pune          79
18         19     Rohit   23    Male   BCom     70    Pune          78
11         12      Ritu   20  Female    BSc     69    Pune          78
46         47    Sachin   20    Male    BCA     69  Mumbai          75
26         27     Harsh   22    Male    BSc     68  Mumbai          74
7           8     Kajal   20  Female    BCA     67  Mumbai          70
16         17    Deepak   20    Male    BCA     66  Mumbai          75
2           3     Rahul   19    Male    BSc     65  Nagpur          75
39         40     Seema   20  Female   BCom     64  Nashik          72
32         33     Sunil   22    Male    BSc     62  Nagpur          68
48         49    Naresh   22    Male   BCom     61    Pune          70
20         21    Manish   20    Male    BSc     60  Mumbai          70
34         35    Sameer   20    Male    BCA     59  Nashik          65
14         15     Karan   19    Male    BSc     58  Nashik          72
42         43     Mohit   20    Male   BCom     56  Nagpur          65
4           5     Arjun   20    Male    BCA     55    Pune          60
24         25     Akash   21    Male   BCom     54  Nashik          60
8           9     Ankit   22    Male    BSc     49    Pune          65
28         29     Nitin   23    Male    BCA     47    Pune          55

In [ ]:
df_pune_students = df[df['City'] == 'Pune']
display(df_pune_students.head(3))

   StudentID   Name  Age  Gender Course  Marks  City  Attendance
1          2   Neha   21  Female    BCA     82  Pune          90
4          5  Arjun   20    Male    BCA     55  Pune          60
8          9  Ankit   22    Male    BSc     49  Pune          65

# Create a new column Result (Pass if Marks >= 50 else Fail)
#Get all students who failed
# Find average Marks city-wise
# Find top 5 students based on Marks
# Create new CSV file of students with Marks > 85
# Find students whose Attendance > 90 AND Marks > 85
# Replace course "BCA" with "Computer Science"
# Save updated DataFrame into a new CSV file

In [ ]:
f_students = df[df['Result'] == 'Fail']
display(f_students)

,StudentID,Name,Age,Gender,Course,Marks,City,Attendance,Result
8,9,Ankit,22,Male,BSc,49,Pune,65,Fail
28,29,Nitin,23,Male,Computer Science,47,Pune,55,Fail

In [ ]:
avg_marks_city= df.groupby('City')['Marks'].mean()
display(avg_marks_city)

City
Mumbai    78.250000
Nagpur    79.400000
Nashik    73.000000
Pune      70.933333
Name: Marks, dtype: float64

In [ ]:
df['Course'] = df['Course'].replace('BCA', 'Computer Science')
display(df.head())

,StudentID,Name,Age,Gender,Course,Marks,City,Attendance,Result
0,1,Amit,20,Male,Computer Science,78,Mumbai,85,Pass
1,2,Neha,21,Female,Computer Science,82,Pune,90,Pass
2,3,Rahul,19,Male,BSc,65,Nagpur,75,Pass
3,4,Pooja,22,Female,BCom,88,Mumbai,92,Pass
4,5,Arjun,20,Male,Computer Science,55,Pune,60,Pass

In [154]:
high_attend_high_marks = df[(df['Attendance'] > 90) & (df['Marks'] > 85)]
display(high_attend_high_marks)

,StudentID,Name,Age,Gender,Course,Marks,City,Attendance,Result
3,4,Pooja,22,Female,BCom,88,Mumbai,92,88
5,6,Sneha,23,Female,BSc,91,Nashik,95,91
12,13,Sahil,23,Male,BCom,90,Nagpur,92,90
17,18,Nisha,22,Female,BSc,92,Nagpur,96,92
22,23,Varun,22,Male,Computer Science,88,Nagpur,91,88
23,24,Shreya,23,Female,BSc,93,Mumbai,97,93
33,34,Rekha,23,Female,BCom,91,Mumbai,94,91
37,38,Swati,23,Female,Computer Science,92,Nagpur,96,92
41,42,Kriti,23,Female,BSc,89,Pune,92,89
47,48,Pallavi,21,Female,BSc,95,Nagpur,98,95
49,50,Riya,23,Female,Computer Science,90,Mumbai,93,90

In [155]:
df[df['Marks'] > 85].to_csv('top_students.csv', index=False)

In [150]:
top_5= df.sort_values(by='Marks', ascending=False).head(5)
display(top_5)

,StudentID,Name,Age,Gender,Course,Marks,City,Attendance,Result
47,48,Pallavi,21,Female,BSc,95,Nagpur,98,Pass
23,24,Shreya,23,Female,BSc,93,Mumbai,97,Pass
17,18,Nisha,22,Female,BSc,92,Nagpur,96,Pass
37,38,Swati,23,Female,Computer Science,92,Nagpur,96,Pass
33,34,Rekha,23,Female,BCom,91,Mumbai,94,Pass